### ISSUE TITLE
Directions: wishes to retrieve the set of instruction texts

### ISSUE THREAD

**Issue by rjcristy** [jd-alexander/Google-Directions-Android#12]
I created one anyway.

    public String[] getDirectionTexts(Document doc) {
        NodeList nl1, nl2;
        
        nl1 = doc.getElementsByTagName("step");
        String[] instructions = null;
        if (nl1.getLength() > 0) {
        	instructions = new String[nl1.getLength()];
            for (int i = 0; i < nl1.getLength(); i++) 
            {
                Node node1 = nl1.item(i);
                nl2 = node1.getChildNodes();

                Node locationNode = nl2.item(getNodeIndex(nl2, "html_instructions"));
                instructions[i] = Html.fromHtml(locationNode.getTextContent()).toString();
                if(isLogging)
           			Log.i("GoogleDirection", "Instructions : " + Html.fromHtml(locationNode.getTextContent()).toString());
            }
        }
        return instructions;
    }    

in GoogleDirection.java

Thank you for your awesome work. Accept this as a sign of my gratitude

**Comment by jd-alexander** [comment]
Thanks will be adding it to the main branch soon
