### ISSUE TITLE
Zooming does not make the path to zoom as well

### ISSUE THREAD

**Issue by megzworld** [jd-alexander/Google-Directions-Android#13]
Hello ,

It is a good library to use in the app. But I noticed a thing about it that
I used it in my app and figured out that it draws a line between two points , but when I zoom the map, the line drawn stays at same location .

can this be solved ?
please let me know.

**Comment by jd-alexander** [comment]
That's the default functionality of the overlay. Hopefully zooming of the line will be implemented in the future but I don't have a tentative time line for this.
