### ISSUE TITLE
Distance bug

### ISSUE THREAD

**Issue by vincentvanzyl** [jd-alexander/Google-Directions-Android#30]
Hi

On line 91 on your GoogleParser class:
segment.setDistance(distance / 1000);

distance is and int and 1000 is also an int and the segment distance is a double. And as a consequence, the distances are not calculated correctly. I have values like 0.0, 1.0, 9.0, etc

You need to cast both to doubles:
segment.setDistance((double)distance / (double)1000); 

Thanks for a great library

**Comment by jd-alexander** [comment]
would be nice if you could submit fix via a pull request

**Comment by vincentvanzyl** [comment]
Ok, done:
https://github.com/jd-alexander/Google-Directions-Android/pull/31

Thanks
