### ISSUE TITLE
How to Get Distance and Time Estimate 

### ISSUE THREAD

**Issue by waqary705** [jd-alexander/Google-Directions-Android#32]
Hi Alex , I want to get Time Estime  , Distance in KM using this library how to get it please help me I'm new in android

**Comment by jd-alexander** [comment]
The library does not currently support that.  Will think about restructuring so that such data can be returned.

**Comment by edwardc1** [comment]
The Google Maps Distance Matrix API have been released. Hope you can add the Get Distance and Time Estimate function into the app. Thanks!
https://developers.google.com/maps/documentation/distance-matrix/intro#Introduction
https://www.youtube.com/watch?v=tXPEOJaeFm8
