### ISSUE TITLE
Runtime Exception: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by rsnirma** [jd-alexander/Google-Directions-Android#37]
11-21 05:58:17.679 7158-7158/com.example.abcde E/AndroidRuntime: FATAL EXCEPTION: main
11-21 05:58:17.679 7158-7158/com.example.abcde E/AndroidRuntime: Process: com.example.abcde, PID: 7158
11-21 05:58:17.679 7158-7158/com.example.abcde E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.abcde/com.example.abcde.ShortestPath.RoadMap}: java.lang.RuntimeException: Unable to bind views for com.example.abcde.ShortestPath.RoadMap
11-21 05:58:17.679 7158-7158/com.example.abcde E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

**Comment by fcduarte** [comment]
Ok so you have a problem with ButterKnife and post it as an issue for the library? Really?

**Comment by jd-alexander** [comment]
LOL. @fcduarte I'm here laughing right now. oh boy.
