### ISSUE TITLE
How to solve gradle syn failed error:(2, 0) defaultmavenfactory

### ISSUE THREAD

**Issue by Code1337** [jd-alexander/Google-Directions-Android#47]
I am getting this error during gradle syn - Error:(2, 0) org/gradle/api/publication/maven/internal/defaultmavenfactory 

error focus onto this
`apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: "com.jfrog.bintray"
 

dependencies {
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
}
// This is the library version used when deploying the artifact
version = "1.0.9"`

**Comment by jd-alexander** [comment]
I am not sure why that error. is happening. I cant reproduce. If you still have it you can reopen issue.

**Comment by edwardc1** [comment]
FYI:
http://stackoverflow.com/questions/32988669/how-to-solve-gradle-sync-failed-error-defaultmavenfactory
